version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/codedeployresources
hooks:
  ApplicationStop:
    - location: application-stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application-start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate-service.sh
      timeout: 300
      runas: root
