version: 0.2

phases:

  build:
    commands:
      - ls
      - cd spring-boot-hello-world-example
      - mvn -Dmaven.test.skip=true clean install
      # - mvn clean install
      # - mvn clean package
      - ls
      - cd target
      - ls

  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - spring-boot-hello-world-example/target/*.war
    - aws/scripts/*.sh
    - appspec.yml
  discard-paths: yes