version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn -Dmaven.test.skip=true clean install 
      # - cd $APP_FOLDER
      # - mvn clean install
      # - mvn clean package
      - ls
      - cd target
      - ls

  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - aws/scripts/*.sh
    - appspec.yml
  discard-paths: yes
