AWSTemplateFormatVersion: 2010-09-09
Description: Template to create DynamoDB tables
Parameters:
  Project:
    Type: String
  App:
    Type: String
    Default: B1Smart
    Description: Name of the app
  AwsEnv:
    Type: String
    Default: dev
    AllowedValues: [dev, tst]
  CollectionsTableName:
    Type: String
    Default: sportworld-nft-collections
    Description: Name of the collection table
  NftDetailsTableName:
    Type: String
    Default: sportworld-nft-details
    Description: Name of the nft details table
  OffchainNftsTableName:
    Type: String
    Default: sportworld-offchain-nfts
    Description: Name of the offchain nfts table
  ContractEventsTableName:
    Type: String
    Default: sportworld-nft-contract-events
    Description: Name of the nft contract events table
  ContractEventsMetadataTableName:
    Type: String
    Default: sportworld-nft-contract-events-metadata
    Description: Name of the nft contract events metadata table
  TasksTableName:
    Type: String
    Default: sportworld-nft-tasks
    Description: Name of the nft tasks table
  TableClass:
    Type: String
    Default: STANDARD
    Description: Table class to be set
  HashKeyElementName:
    Type: String
    Default: id
    Description: Hash Key Name
  HashKeyElementType:
    Type: String
    Default: S
    Description: Hash Key Type
  RangeKeyElementName:
    Type: String
    Default: updatedAt
    Description: Range Key Name
  RangeKeyElementType:
    Type: String
    Default: N
    Description: Range Key Type
  BillingMode:
    Type: String
    Default: PAY_PER_REQUEST
    Description: Billing Mode Type
  ContributorInsightsSpecification:
    Type: String
    Default: false
    Description: Contributor Insights Specifications
  EnableDeletionProtection:
    Type: String
    Default: false
    Description: Enable Deletion Protection
  EnablePointInTimeRecovery:
    Type: String
    Default: false
    Description: Enable Point In Time Recovery
Resources:
  CollectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: 'HASH'
      BillingMode: !Ref BillingMode
      ContributorInsightsSpecification:
        Enabled: !Ref ContributorInsightsSpecification
      DeletionProtectionEnabled: !Ref EnableDeletionProtection
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref EnablePointInTimeRecovery
      TableClass: !Ref TableClass
      TableName: !Ref CollectionsTableName
      Tags:
        - Key: 'Project'
          Value: !Ref Project
        - Key: 'App'
          Value: !Ref App
        - Key: 'AwsEnv'
          Value: !Ref AwsEnv

  NftDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
        - AttributeName: !Ref RangeKeyElementName
          AttributeType: !Ref RangeKeyElementType
        - AttributeName: parentId
          AttributeType: S
        - AttributeName: collection
          AttributeType: S
        - AttributeName: ownerAddress
          AttributeType: S
        - AttributeName: contractAddress
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: 'HASH'
      BillingMode: !Ref BillingMode
      ContributorInsightsSpecification:
        Enabled: !Ref ContributorInsightsSpecification
      DeletionProtectionEnabled: !Ref EnableDeletionProtection
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref EnablePointInTimeRecovery
      TableClass: !Ref TableClass
      TableName: !Ref NftDetailsTableName
      GlobalSecondaryIndexes:
        - IndexName: 'ParentIdIndex'
          KeySchema:
            - AttributeName: 'parentId'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
        - IndexName: 'OwnerAddressIndex'
          KeySchema:
            - AttributeName: 'ownerAddress'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
        - IndexName: 'CollectionIndex'
          KeySchema:
            - AttributeName: 'collection'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
        - IndexName: 'ContractIndex'
          KeySchema:
            - AttributeName: 'contractAddress'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: 'Project'
          Value: !Ref Project
        - Key: 'App'
          Value: !Ref App
        - Key: 'AwsEnv'
          Value: !Ref AwsEnv

  ContractEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
        - AttributeName: !Ref RangeKeyElementName
          AttributeType: !Ref RangeKeyElementType
        - AttributeName: nftId
          AttributeType: S
        - AttributeName: to
          AttributeType: S
        - AttributeName: from
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: 'HASH'
      BillingMode: !Ref BillingMode
      ContributorInsightsSpecification:
        Enabled: !Ref ContributorInsightsSpecification
      DeletionProtectionEnabled: !Ref EnableDeletionProtection
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref EnablePointInTimeRecovery
      TableClass: !Ref TableClass
      TableName: !Ref ContractEventsTableName
      GlobalSecondaryIndexes:
        - IndexName: 'NftIdIndex'
          KeySchema:
            - AttributeName: 'nftId'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
        - IndexName: 'ToIndex'
          KeySchema:
            - AttributeName: 'to'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
        - IndexName: 'FromIndex'
          KeySchema:
            - AttributeName: 'from'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: 'Project'
          Value: !Ref Project
        - Key: 'App'
          Value: !Ref App
        - Key: 'AwsEnv'
          Value: !Ref AwsEnv

  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: 'HASH'
      BillingMode: !Ref BillingMode
      ContributorInsightsSpecification:
        Enabled: !Ref ContributorInsightsSpecification
      DeletionProtectionEnabled: !Ref EnableDeletionProtection
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref EnablePointInTimeRecovery
      TableClass: !Ref TableClass
      TableName: !Ref TasksTableName
      Tags:
        - Key: 'Project'
          Value: !Ref Project
        - Key: 'App'
          Value: !Ref App
        - Key: 'AwsEnv'
          Value: !Ref AwsEnv

  ContractEventsMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: 'HASH'
      BillingMode: !Ref BillingMode
      ContributorInsightsSpecification:
        Enabled: !Ref ContributorInsightsSpecification
      DeletionProtectionEnabled: !Ref EnableDeletionProtection
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref EnablePointInTimeRecovery
      TableClass: !Ref TableClass
      TableName: !Ref ContractEventsMetadataTableName
      Tags:
        - Key: 'Project'
          Value: !Ref Project
        - Key: 'App'
          Value: !Ref App
        - Key: 'AwsEnv'
          Value: !Ref AwsEnv

  OffchainNftsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
        - AttributeName: !Ref RangeKeyElementName
          AttributeType: !Ref RangeKeyElementType
        - AttributeName: parentId
          AttributeType: S
        - AttributeName: collection
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref HashKeyElementName
          KeyType: 'HASH'
      BillingMode: !Ref BillingMode
      ContributorInsightsSpecification:
        Enabled: !Ref ContributorInsightsSpecification
      DeletionProtectionEnabled: !Ref EnableDeletionProtection
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref EnablePointInTimeRecovery
      TableClass: !Ref TableClass
      TableClass: 'STANDARD'
      TableName: !Ref OffchainNftsTableName
      GlobalSecondaryIndexes:
        - IndexName: 'ParentIdIndex'
          KeySchema:
            - AttributeName: 'parentId'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
        - IndexName: 'CollectionIndex'
          KeySchema:
            - AttributeName: 'collection'
              KeyType: 'HASH'
            - AttributeName: 'updatedAt'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: 'Project'
          Value: !Ref Project
        - Key: 'App'
          Value: !Ref App
        - Key: 'AwsEnv'
          Value: !Ref AwsEnv
