AWSTemplateFormatVersion: 2010-09-09
Parameters:
  project:
    Type: String
    Description: Name of the project
  app:
    Type: String
    Description: Name of the application
  awsEnv:
    Type: String
    AllowedValues: [dev, dev01, int, int01, uat, uat01, prd, prd01,stage,stag01,test,prod,dr] 
  codeStarConnectionId:
    Type: String
    NoEcho: true
    Description: "Code Star Connection Id"
  gitHubOwner:
    Type: String
    Default: ''
  githubRepositoryName:
    Type: String
    Description: Specify repo name for pipeline
  githubBranch:
    Type: String
    Description: Specify brnach name for pipeline        
  cbProject: 
    Type: String
    Description: Specify codebuild project      
  codePipelineBucket:
    Type: String
    Description: Specify bucket name for artifacts
  iamServiceRole:
    Type: String
  codePipelineAppName:
    Type: String
    Default: ''
    Description: Application name for code pipeline
  applicationName:
    Type: String
  deploymentGroupName:
    Type: String

Conditions:
  hasCodePipelineAppName: !Not [ !Equals [!Ref codePipelineAppName, '']]
  
Resources:
  cpApp:
    Type: AWS::CodePipeline::Pipeline
    Properties:
        ArtifactStore: 
            Location: !Ref codePipelineBucket
            Type: S3
        Name: !If
        - hasCodePipelineAppName
        - !Ref codePipelineAppName
        - !Sub "${project}-${awsEnv}-${githubRepositoryName}-${githubBranch}-${AWS::Region}"
        RoleArn: !Ref iamServiceRole
        Stages:
            - 
              Name: Source
              Actions:
                - Name: Source
                  ActionTypeId:
                    Category: Source
                    Owner: AWS
                    Version: '1'
                    Provider: CodeStarSourceConnection
                  Configuration:
                    ConnectionArn: !Sub "arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/${codeStarConnectionId}"
                    BranchName: !Ref githubBranch
                    FullRepositoryId: !Sub ${gitHubOwner}/${githubRepositoryName}
                  OutputArtifacts:
                    - Name: SourceArtifact
            - 
              Name: Build
              Actions:
                - 
                  Name: CodeBuild
                  ActionTypeId:
                    Category: Build
                    Owner: AWS
                    Provider: CodeBuild
                    Version: '1'
                  Configuration:
                    ProjectName: !Ref cbProject
                  InputArtifacts:
                    - Name: SourceArtifact
                  OutputArtifacts:
                    - Name: BuildArtifact
            - 
              Name: Deploy
              Actions:
                - 
                  Name: DeployAction
                  ActionTypeId:
                    Category: Deploy
                    Owner: AWS
                    Provider: CodeDeploy
                    Version: '1'
                  Configuration:
                    ApplicationName: !Ref applicationName
                    DeploymentGroupName: !Ref deploymentGroupName
                  InputArtifacts:
                    - Name: BuildArtifact     
Outputs:
  cpApp:
    Description: CodePipeline App
    Value: !Ref cpApp
    Export: 
      Name: !If
      - hasCodePipelineAppName
      - !Ref codePipelineAppName
      - !Sub "${project}-${app}-${awsEnv}-codepipeline-${AWS::Region}"

